"""barang table

Revision ID: 19ad443a98a3
Revises: 4ad64b107185
Create Date: 2018-08-05 19:53:47.943334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ad443a98a3'
down_revision = '4ad64b107185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namabarang', sa.String(length=120), nullable=True),
    sa.Column('jumlahbarang', sa.Integer(), nullable=True),
    sa.Column('harga', sa.Integer(), nullable=True),
    sa.Column('idHimpunan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idHimpunan'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventori_harga'), 'inventori', ['harga'], unique=False)
    op.create_index(op.f('ix_inventori_jumlahbarang'), 'inventori', ['jumlahbarang'], unique=False)
    op.create_index(op.f('ix_inventori_namabarang'), 'inventori', ['namabarang'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventori_namabarang'), table_name='inventori')
    op.drop_index(op.f('ix_inventori_jumlahbarang'), table_name='inventori')
    op.drop_index(op.f('ix_inventori_harga'), table_name='inventori')
    op.drop_table('inventori')
    # ### end Alembic commands ###
